name: Terraform Checks

on:
  pull_request:
    paths:
      - 'terraform/**.tf'
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: Terraform Validation & Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: terraform

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: terraform

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1

      - name: Run TFLint
        run: |
          tflint --init
          tflint
        working-directory: terraform

      - name: Install checkov
        run: pip3 install checkov
        working-directory: terraform

      - name: Run checkov
        run: checkov -f *.tf --skip-check CKV_AZURE_50 --skip-check CKV2_AZURE_31
        working-directory: terraform


