version: v3
teleport:
  nodename: t-sec-902
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text

auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex

ssh_service:
  enabled: "yes"

proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3080
  web_listen_addr: 0.0.0.0:443
  public_addr: teleport.ecotecknik.fr:443
  acme:
    enabled: false
  https_keypairs:
    - key_file: /var/lib/teleport/webproxy_key.pem
      cert_file: /var/lib/teleport/webproxy_cert.pem

